sudo: required
services:
   - docker


before_install:
   - docker build -t masmirzaei/fluffy-parakeet -f Dockerfile.dev .


script:
   - docker run masmirzaei/fluffy-parakeet npm run test -- --coverage

